package com.wd.daquan.common.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

import java.io.Serializable;

/**
 * Entity mapped to table GROUP_MEMBER.
 */
public class CNOSSFileBean implements Serializable {
    private static final long serialVersionUID = -1L;

    public String host;
    public String requestId;
    public String eTag;
    public String fileName;
    public String localFile;
    public CollectionUploadMsgBean collectionUploadMsgBean;

}
